/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author Iury Silva
 */
public class TelaTipoTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTipoTriangulo
     */
    public TelaTipoTriangulo() {
        initComponents();
        panelTipoTriangulo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sldSegmentoAb = new javax.swing.JSlider();
        sldSegmentoBc = new javax.swing.JSlider();
        sldSegmentoCa = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        panelTipoTriangulo = new javax.swing.JPanel();
        lblStatusFormaOuNao = new javax.swing.JLabel();
        lblTipoTriangulo = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        lblSegmentoAb = new javax.swing.JLabel();
        lblSegmentoBc = new javax.swing.JLabel();
        lblSegmentoCa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Segmento AB: ");

        jLabel2.setText("Segmento BC: ");

        jLabel3.setText("Segmento CA: ");

        sldSegmentoAb.setMaximum(20);
        sldSegmentoAb.setValue(0);
        sldSegmentoAb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSegmentoAbStateChanged(evt);
            }
        });

        sldSegmentoBc.setMaximum(20);
        sldSegmentoBc.setValue(0);
        sldSegmentoBc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSegmentoBcStateChanged(evt);
            }
        });

        sldSegmentoCa.setMaximum(20);
        sldSegmentoCa.setValue(0);
        sldSegmentoCa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSegmentoCaStateChanged(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PngJoy_triangulo-triangulo-abc-png-download_10350770 (3).png"))); // NOI18N

        lblStatusFormaOuNao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblStatusFormaOuNao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusFormaOuNao.setText("Forma ou não?");

        lblTipoTriangulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTipoTriangulo.setForeground(new java.awt.Color(255, 102, 102));
        lblTipoTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoTriangulo.setText("Tipo de Triângulo");

        javax.swing.GroupLayout panelTipoTrianguloLayout = new javax.swing.GroupLayout(panelTipoTriangulo);
        panelTipoTriangulo.setLayout(panelTipoTrianguloLayout);
        panelTipoTrianguloLayout.setHorizontalGroup(
            panelTipoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoTrianguloLayout.createSequentialGroup()
                .addGroup(panelTipoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusFormaOuNao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTipoTrianguloLayout.setVerticalGroup(
            panelTipoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusFormaOuNao)
                .addGap(29, 29, 29)
                .addComponent(lblTipoTriangulo)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblSegmentoAb.setText("0");

        lblSegmentoBc.setText("0");

        lblSegmentoCa.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldSegmentoAb, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(sldSegmentoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(sldSegmentoBc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSegmentoAb, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(lblSegmentoBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSegmentoCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(sldSegmentoAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegmentoAb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(sldSegmentoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegmentoBc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(sldSegmentoCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSegmentoCa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addComponent(btnVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        int segmentoAb = sldSegmentoAb.getValue();
        int segmentoBc = sldSegmentoBc.getValue();
        int segmentoCa = sldSegmentoCa.getValue();
        
        if(segmentoAb < (segmentoBc + segmentoCa) && segmentoBc < (segmentoAb + segmentoCa) && segmentoCa < (segmentoBc + segmentoAb)){
            lblStatusFormaOuNao.setText("Formam um triângulo!");
            if(segmentoAb == segmentoBc && segmentoAb == segmentoCa){
                lblTipoTriangulo.setText("Triângulo Equilátero.");
            }else if(segmentoAb != segmentoBc && segmentoBc != segmentoCa && segmentoCa != segmentoAb){
                lblTipoTriangulo.setText("Triãngulo Escaleno.");
            }else{
                lblTipoTriangulo.setText("Triângulo Isósceles.");
            } 
        }else{
            lblStatusFormaOuNao.setText("Não forma um triangulo.");
            lblTipoTriangulo.setText("-----");
            //lblTipoTriangulo.setVisible(false);
        }
        panelTipoTriangulo.setVisible(true);
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void sldSegmentoAbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSegmentoAbStateChanged
        // TODO add your handling code here:
        lblSegmentoAb.setText(Integer.toString(sldSegmentoAb.getValue()));
    }//GEN-LAST:event_sldSegmentoAbStateChanged

    private void sldSegmentoBcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSegmentoBcStateChanged
        // TODO add your handling code here:
        lblSegmentoBc.setText(Integer.toString(sldSegmentoBc.getValue()));
    }//GEN-LAST:event_sldSegmentoBcStateChanged

    private void sldSegmentoCaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSegmentoCaStateChanged
        // TODO add your handling code here:
        lblSegmentoCa.setText(Integer.toString(sldSegmentoCa.getValue()));
    }//GEN-LAST:event_sldSegmentoCaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTipoTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSegmentoAb;
    private javax.swing.JLabel lblSegmentoBc;
    private javax.swing.JLabel lblSegmentoCa;
    private javax.swing.JLabel lblStatusFormaOuNao;
    private javax.swing.JLabel lblTipoTriangulo;
    private javax.swing.JPanel panelTipoTriangulo;
    private javax.swing.JSlider sldSegmentoAb;
    private javax.swing.JSlider sldSegmentoBc;
    private javax.swing.JSlider sldSegmentoCa;
    // End of variables declaration//GEN-END:variables
}
