/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;
/**
 *
 * @author Iury Silva
 */
public class CalculadoraComMathSwing extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraComMathSwing
     */
    public CalculadoraComMathSwing() {//CONTRUTOR DA TELA 
        initComponents();
        painelCalculadora.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        spnValor = new javax.swing.JSpinner();
        painelCalculadora = new javax.swing.JPanel();
        lblPotenciaMensagem1 = new javax.swing.JLabel();
        lblRaizCuboMensagem1 = new javax.swing.JLabel();
        lblValorAbsolutoMensagem1 = new javax.swing.JLabel();
        lblRestoDiviMensagem1 = new javax.swing.JLabel();
        lblRaizMensagem1 = new javax.swing.JLabel();
        lblResultadoRestoDivi = new javax.swing.JLabel();
        lblResultadoPotencia = new javax.swing.JLabel();
        lblResultadoRaizQuadrada = new javax.swing.JLabel();
        lblResultadoRaizCubo = new javax.swing.JLabel();
        lblResultadoValorAbsoluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Calculadora Usando Math");

        jLabel2.setText("Informe  um valor:");

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator (3).png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, -50, 500, 1));
        spnValor.setOpaque(false);

        lblPotenciaMensagem1.setText("Valor Elevado ao Cubo:");

        lblRaizCuboMensagem1.setText("Raiz Cúbica:");

        lblValorAbsolutoMensagem1.setText("Valor Absoluto:");

        lblRestoDiviMensagem1.setText("Resto da Divisão por 2:");

        lblRaizMensagem1.setText("Raiz Quadrada:");

        lblResultadoRestoDivi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoRestoDivi.setForeground(new java.awt.Color(0, 0, 255));
        lblResultadoRestoDivi.setText("0");

        lblResultadoPotencia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoPotencia.setForeground(new java.awt.Color(0, 0, 255));
        lblResultadoPotencia.setText("0");

        lblResultadoRaizQuadrada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoRaizQuadrada.setForeground(new java.awt.Color(0, 0, 255));
        lblResultadoRaizQuadrada.setText("0");

        lblResultadoRaizCubo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoRaizCubo.setForeground(new java.awt.Color(0, 0, 255));
        lblResultadoRaizCubo.setText("0");

        lblResultadoValorAbsoluto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoValorAbsoluto.setForeground(new java.awt.Color(0, 0, 255));
        lblResultadoValorAbsoluto.setText("0");

        javax.swing.GroupLayout painelCalculadoraLayout = new javax.swing.GroupLayout(painelCalculadora);
        painelCalculadora.setLayout(painelCalculadoraLayout);
        painelCalculadoraLayout.setHorizontalGroup(
            painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPotenciaMensagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(lblRestoDiviMensagem1)
                    .addComponent(lblRaizMensagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRaizCuboMensagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorAbsolutoMensagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCalculadoraLayout.createSequentialGroup()
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultadoRaizCubo, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(lblResultadoPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultadoRestoDivi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultadoValorAbsoluto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(painelCalculadoraLayout.createSequentialGroup()
                        .addComponent(lblResultadoRaizQuadrada, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        painelCalculadoraLayout.setVerticalGroup(
            painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculadoraLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestoDiviMensagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoRestoDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPotenciaMensagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizMensagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizCuboMensagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoRaizCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorAbsolutoMensagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcular)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCalcular)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
        int valorInformado = Integer.parseInt(spnValor.getValue().toString());
        
        //Resto da Divisão  por 2
        int resto = valorInformado % 2;
        lblResultadoRestoDivi.setText(Integer.toString(resto));
        
        //Valor elevado ao Cubo
        double potencia = Math.pow(valorInformado, 3);
        lblResultadoPotencia.setText(Double.toString(potencia));
        
        double raizQuadrada = Math.sqrt(valorInformado);
        lblResultadoRaizQuadrada.setText(String.format("%.3f",raizQuadrada));
        
        double raizCubica = Math.cbrt(valorInformado);
        lblResultadoRaizCubo.setText(String.format("%.3f",raizCubica));
        
        float valorAbsoluto = Math.abs(valorInformado);
        lblResultadoValorAbsoluto.setText(Float.toString(valorAbsoluto));
        
        painelCalculadora.setVisible(true);
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraComMathSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraComMathSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraComMathSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraComMathSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraComMathSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPotenciaMensagem1;
    private javax.swing.JLabel lblRaizCuboMensagem1;
    private javax.swing.JLabel lblRaizMensagem1;
    private javax.swing.JLabel lblRestoDiviMensagem1;
    private javax.swing.JLabel lblResultadoPotencia;
    private javax.swing.JLabel lblResultadoRaizCubo;
    private javax.swing.JLabel lblResultadoRaizQuadrada;
    private javax.swing.JLabel lblResultadoRestoDivi;
    private javax.swing.JLabel lblResultadoValorAbsoluto;
    private javax.swing.JLabel lblValorAbsolutoMensagem1;
    private javax.swing.JPanel painelCalculadora;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
